[project]
name = "nged_substation_forecast_local"
requires-python = ">=3.14"
version = "0.1.0"
dependencies = [
    "dagster==1.12.11",
    "dagster-webserver",
    "dagster-dg-cli",
]

[tool.dg]
directory_type = "deployment"


