[project]
name = "data-nged"
version = "0.0.1"
description = "Logic for downloading and prepping NGED data"
requires-python = ">=3.14"
dependencies = [
    "contracts",
    "requests>=2.31.0",
    "polars>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
contracts = { workspace = true }
