[project]
name = "dynamical-data"
version = "0.1.0"
description = "Download & process NWPs from Dynamical.org"
readme = "README.md"
authors = [
    { name = "Jack Kelly", email = "jack@openclimatefix.org" }
]
requires-python = ">=3.14"
dependencies = [
    "icechunk>=1.1.18",
    "marimo>=0.19.9",
    "matplotlib>=3.10.8",
    "scipy>=1.17.0",  # Only required for smoothing matplotlib. TODO(Jack): Remove!
    "xarray>=2026.1.0",
]

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
